### ISSUE TITLE
bug of run_mask_finetune_raft.sh

### ISSUE THREAD

**Issue by MGDDestiny** [avalonstrel/AdaptiveMA#1]
**_运行run_mask_finetune_raft.sh文件时一直有问题，许久都没有解决，希望解惑，非常感谢！_**
**在修改run_mask_finetune_raft.sh文件至如下并运行时：**

approach=mask_norm_sigmoid_linear
mask_level=layerwise
lr=2e-5
warp_init_val=0.2
reg_alpha=1e-4
sum_reg_type=0.2
epsilon=0.2
gpu_ids="0"

port=29500

exp_id=${approach}_${mask_level}_ft_raft_${lr}_${warp_init_val}_reg${reg_alpha}_sr${sum_reg_type}_eps${epsilon}_ep1
project_dir=$(cd "$(dirname $0)"/..; pwd)/../..
log_dir=${project_dir}/log/${exp_id}
model_path=/webdav/MyData/Qwen1.5-1.8B
output_dir=${model_path}/mask_opt/${exp_id}
dataset_path=/home/student2021/syq/AMA

if [ ! -d "${output_dir}" ];
then
  mkdir -p ${output_dir}
fi

if [ ! -d "${log_dir}" ];
then
  mkdir -p ${log_dir}
fi
#原代码 accelerate launch --main_process_port ${port} --gpu_ids=${gpu_ids}
accelerate launch /home/student2021/syq/AdaptiveMA/examples/finetune_mask.py \
    --model_name_or_path ${model_path} \
    --dataset_path ${dataset_path} \
    --output_dir ${output_dir} --overwrite_output_dir \
    --num_train_epochs 1 \
    --learning_rate ${lr}\
    --block_size 512 \
    --per_device_train_batch_size 2 \
    --fp16 \
    --run_name ${exp_id} \
    --validation_split_percentage 0 \
    --logging_steps 20 \
    --approach ${approach} \
    --reg_alpha ${reg_alpha} \
    --sum_reg_type ${sum_reg_type} \
    --epsilon ${epsilon} \
    --mask_level ${mask_level} \
    --do_train \
    --ddp_timeout 72000 \
    --save_steps 1000 \
    --dataloader_num_workers 4 \
    | tee ${log_dir}/train.log \
    2> ${log_dir}/train.err

**会出现如下报错：**
Traceback (most recent call last):                                                                                                                                    
  File "/home/student2021/syq/AdaptiveMA/examples/finetune_mask.py", line 82, in <module>                                                                             
    main()                                                                                                                                                            
  File "/home/student2021/syq/AdaptiveMA/examples/finetune_mask.py", line 78, in main
    tuned_model = finetuner.tune(model0=model0, model1=model1, dataset=dataset)
  File "/home/student2021/syq/AdaptiveMA/src/lmflow/pipeline/mask_finetuner.py", line 306, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/trainer.py", line 2262, in _inner_training_loop
    _grad_norm = self.accelerator.clip_grad_norm_(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/accelerate/accelerator.py", line 2269, in clip_grad_norm_
    self.unscale_gradients()
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/accelerate/accelerator.py", line 2219, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 307, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 248, in _unscale_grads_
    torch._amp_foreach_non_finite_check_and_unscale_(
**NotImplementedError: Could not run 'aten::_amp_foreach_non_finite_check_and_unscale_' with arguments from the 'CPU' backend.** This could be because the operator doesn'
t exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, pl
ease visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_amp_foreach_non_finite_check_and_unscale_' is only available for these backends: [CUDA, Meta,
BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA
, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, Auto
gradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper,
PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

**如若不使用accelerate改成python /home/student2021/syq/AdaptiveMA/examples/finetune_mask.py 会产生另外一种报错：**
Original Traceback (most recent call last):
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1149, in forward
    outputs = self.model(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1034, in forward
    layer_outputs = decoder_layer(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 748, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 644, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student2021/anaconda3/envs/ama_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student2021/syq/AdaptiveMA/src/lmflow/pipeline/utils/mask_trainer.py", line 83, in forward
    self.weight * normalized_alpha + (1 - normalized_alpha) * self.wise_weight,
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!**

**但是在mask_trainer.py文件里面，我已经让所有的tensor都转移到同样的device上了，代码如下：**
    def forward(self, input):
        input = input.to(self.device,dtype=self.dtype)
        epsilon = self.epsilon
        normalized_alpha = self.init_val * (F.sigmoid(self.wise_weight_alpha) + epsilon) / sum([F.sigmoid(alpha) + epsilon for alpha in self.normalized_alphas]) * len(self.normalized_alphas)
        normalized_alpha = normalized_alpha.to(self.device,dtype=self.dtype)
        if self.bias is None:
            return F.linear(input, 
                            self.weight * normalized_alpha + (1 - normalized_alpha) * self.wise_weight,
                            self.bias)
        else:
            normalized_bias_alpha = self.init_val * (F.sigmoid(self.wise_bias_alpha) + epsilon) / sum([F.sigmoid(alpha) + epsilon for alpha in self.normalized_alphas]) * len(self.normalized_alphas)
            # print('weight:',self.weight.device)
            # print('alpha:',normalized_alpha.device)
            # print('wise_weight:',self.wise_weight.device)
            # print(self.weight * normalized_alpha + (1 - normalized_alpha) * self.wise_weight)
            return F.linear(input, 
                            self.weight * normalized_alpha + (1 - normalized_alpha) * self.wise_weight,
                            self.bias * normalized_bias_alpha + (1 - normalized_bias_alpha) * self.wise_bias)

**Comment by avalonstrel** [comment]
helllo, 这个最后的你有检查过bias相关的tensor的device么，或者你运行的时候指定一个gpu会有问题么
